### ISSUE TITLE
mt_stack gives error that data types do not match

### ISSUE THREAD

**Issue by andreakoelzsch** [movestore/Upload-File-from-Local#1]
@annescharf 
Hi Anne, a first version of Local Upload here :)
It works so far, whenever mt_stack() is not needed, but not if data sets have to be combined. Lets talk about, what I have missed, next week.
Merci!

Error in (function (..., .ptype = NULL, .name_spec = NULL, .name_repair = c("minimal", :
Can't combine `..1` <factor<7244e>> and `..2` <integer>.

**Comment by annescharf** [comment]
Hi @andreakoelzsch, shall I look at the main or at the branch, or wait a bit? :)

**Comment by andreakoelzsch** [comment]
@annescharf Hi Anne, gern hier schauen (ich kann da heute und ohne dich erstmal nicht so einfach weitermachen ;)), kann auch direkt auf main, da ich noch nichts eingereicht habe. Wie du meinst, dass es hinterher am besten nachvervolgbar ist. Merci!

**Comment by annescharf** [comment]
solved

**Comment by andreakoelzsch** [comment]
HI @annescharf , sorry, aber bei mir lokal gibt es immer noch den Fehler s.u., sobald ich mt_stack() benutze. Lass uns gern Mittwoch gemeinsam drauf schauen. Vielleicht sind ja auch nur meine Input-files komisch. Ich hänge sie hier mal an. Bis dann und dann für all die Verbesserungen!
Error in dplyr::bind_rows(lapply(dots, mt_track_data)) :
Can't combine `..1$tag.local.identifier` <character> and `..2$tag.local.identifier` <integer>.

**Comment by annescharf** [comment]
Hi @andreakoelzsch, da ist mir was durch die lappen gegangen. Funktion ist mt_stack () und nicht bind_rows()

**Comment by annescharf** [comment]
sorry @andreakoelzsch, ich lag falsch. Ich glaube ich weiß wo das problem liegt, muss aber noch ein bisschen rum testen. Hat eventuell was mit diesem Fehler zu tun
 ````
Error in `mt_stack()`:
! The `track_id_column` differs between the objects to stack and renaming would overwrite existing data.
````
Muss aber noch ein bisschen ausprobieren.

**Comment by andreakoelzsch** [comment]
is fixed now with update of move2 package
